/*  ::

    :: Theme        : Jets
    :: Theme URI    : https://labs.funcoders.com/html/Jets

    :: File         : theme.js
    :: About        : Main js file
    :: Version      : 1.3.1

    NOTE!!! Do not edit this file. Use another script file for changing this or creating new scripts. !!!

:: */

var widthMobile = 992,
    isMobile    = (/android|webos|iphone|ipad|ipod|blackberry|iemobile|opera mini/i.test(navigator.userAgent.toLowerCase()));

$.fn.resizeComplete = function(func, ms, method) {

    // Function body
    var timer = 0;
    this.resize(function() {
        clearTimeout(timer);
        timer = setTimeout(func, ms);
    });

    if (method === 'init') { // Call without method
        func();
    } else if (method === 'load') { // Call function on Window load
        this.on('load', function() {
            func();
        });
    } else if (method === 'ready') { // Call function on DOM ready
        $(function() {
            func();
        });
    }
};

/*  :::::::::: */
/*  :: CORE :: */
/*  :::::::::: */
var Jets = {

    init: function() {

        /* Detect mobile */
        this.mobile();

        if ($('#header').length) {

            /* Header */
            this.header();

            /* Navigation */
            this.nav.carret();
            this.nav.smartMenu();
            this.nav.customMenu();
            this.nav.megamenuCategory();
            this.nav.search();
            this.nav.mobile();
        }

        /* Page header */
        this.page_header.animation();

        /* Container */
        this.container.fullWidth();

        this.shortcodes.slider();

        /* Features */
        this.features.lightbox();
        this.features.tooltip();
        this.features.placeholder();
        this.features.grid();
        this.features.comments();
        this.features.form();

        /* Shortcodes */
        this.shortcodes.teaser();
        this.shortcodes.alertsMessages();
        this.shortcodes.testimonial();
        this.shortcodes.tab(window, jQuery);
        this.shortcodes.accordion(window, jQuery);
        this.shortcodes.carousel();

        /* Other */
        this.other.filter();
        this.other.project();
        this.other.twitter();
        this.other.flickr();
        this.other.animation();
        this.other.counter();
        this.other.skill();
        this.other.toTop();
        this.other.registerLogin();
        this.other.sideOptions();
    },
    mobile: function() {
        if (isMobile) { $('html').addClass('mobile'); }
    },
    header: function() {

        // Header defaults
        var $header = $('#header'),
            header = {
                nav    : $('.navbar:not(.parallax-off) #main-menu > li'),
                navbar : $('.navbar:not(.parallax-off) .navbar-inner'),
                logo   : $('.navbar:not(.parallax-off) .logo'),
                topbar : $('.topbar')
            },
            items = false,
            t,
            parallax;

        // Header parallax function
        function header_init() {

            // Check if non mobile screen
            if ($(window).width() < widthMobile) { items = false; return false; }

            if (items === false) {

                var navBottom     = header.nav.length ? parseInt(header.nav.removeAttr('style').css('padding-bottom'), 10) : 0,
                    navbarTop     = header.navbar.length ? parseInt(header.navbar.removeAttr('style').css('margin-top'), 10) : 0,
                   logoHeight    = '65';//logoHeight    = header.logo.length ? header.logo.removeAttr('style').height() : 0,
                    topbarHeight  = header.topbar.length ? parseInt(header.topbar.removeAttr('style').css('height'), 10) : 0;
					

                items = [{
                    target : header.nav,
                    start  : topbarHeight,
                    css    : 'padding-bottom',
                    max    : navBottom,
                    min    : navBottom / 2,
                    ratio  : 2
                }, {
                    target : header.navbar,
                    start  : topbarHeight,
                    css    : 'margin-top',
                    max    : navbarTop,
                    min    : navbarTop / 0,
                    ratio  : 2
                }, {
                    target : header.topbar,
                    start  : 0,
                    css    : 'margin-top',
                    max    : 0,
                    min    : -1 * topbarHeight,
                    ratio  : 1
                }, {
                    target : header.logo,
                    start  : topbarHeight,
                    css    : 'height',
                    max    : logoHeight,
                    min    : logoHeight / 1,
                    ratio  : 2
                }];

                $('#header-space').height($header.height());
            }

            t = $(window).scrollTop();

            // Run parallax script
            $.each(items, function(key, obj) {
                if (obj.max !== obj.min) {
                    if (t - obj.start <= 0) {
                        parallax = obj.max;
                    } else if (t - obj.start >= (obj.max - obj.min) * obj.ratio) {
                        parallax = obj.min;
                    } else {
                        parallax = obj.max - (t - obj.start) / obj.ratio;
                    }
                    obj.target.css(obj.css, parallax);
                }
            });

            // Set scroll class to body
            if (t === 0) { $('html').removeClass('scroll'); } else {
                if (!$('html').is('.scroll')) { $('html').addClass('scroll'); }
            }
        }

        if (!$header.is('.sticky-off')) {

            $header.after('<div id="header-space"></div>');
            $('#header-space').height($header.addClass('sticky').height());

            // Call
            $(window).scroll(header_init).resizeComplete(header_init, 50, 'init');
        }
    },
    nav: {
        carret: function() {
            $('#main-menu > li, #main-menu ul.dropdown > li').each(function() {
                if ($(this).children('ul.dropdown').length) {
                    $(this).children('a').addClass('carret').prepend('<i class="carret"></i>');
                }
            });
        },
        customMenu: function() {

            var $customMenu = $('#main-menu.custom'), $customMenuBg;

            if ($customMenu.length) {

                $('#header').append('<div id="custom-nav-bg"></div>');
                $customMenuBg = $('#custom-nav-bg');

                $('body').delegate($customMenu, 'update', function() {

                    var $that = $(this),
                        visibleUl = $('ul.dropdown', $customMenu).filter(function() {
                            return $(this).css('visibility') === 'visible';
                        }).add($('li:hover', $that).children('ul.dropdown')),
                        h = 0,
                        f,
                        b = [],
                        i;

                    if (visibleUl.length) {
                        f = $(visibleUl[0]).offset().top;           // get first children offset top

                        for (i = 0; i < visibleUl.length; i += 1) {
                            b.push($(visibleUl[i]).offset().top + $(visibleUl[i]).outerHeight(true) - f);
                        }

                        h = Math.max.apply(Math, b);                // get MAX height
                    }

                    $customMenuBg.height(h);

                }).delegate($customMenu, 'hide', function() {
                    $customMenuBg.removeAttr('style');
                });

                $(' > li,ul.dropdown > li', $customMenu).on('mouseenter', function() {
                    if ($(window).width() >= widthMobile) {
                        $customMenu.trigger('update');
                    }
                });

                $customMenu.on('mouseleave', function() {
                    $(this).trigger('hide');
                });

                $(window).resizeComplete(function() {
                    $customMenu.trigger('hide');
                }, 40);
            }
        },
        smartMenu: function() {

            $(window).resizeComplete(function() {

                if (this.outerWidth < widthMobile) {
                    $('#main-menu').find('> li, ul.dropdown').removeClass('rtl').removeAttr('style');
                    return false;
                }

                var maxLeft         = $('.navbar').offset().left + $('.navbar').outerWidth();

                $('#main-menu > li:not(.megamenu)').each(function() {

                    var $that     = $(this),

                        parentOLeft = $that.offset().left,
                        $dropdown = $that.children('ul.dropdown'),
                        depth     = 0,
                        curLeft;

                    $('li:not(:has(ul.dropdown))', $that).each(function() {
                        var cur = $(this).parents('ul.dropdown').length;
                        if (cur > depth) { depth = cur; }
                    });

                    curLeft = parentOLeft + $dropdown.outerWidth();

                    if (curLeft > maxLeft) {
                        $that.addClass('rtl');
                    } else {
                        $that.removeClass('rtl');
                    }

                    if (depth > 1) {
                        curLeft += $('ul.dropdown ul.dropdown', $that).outerWidth();

                        if (curLeft > maxLeft) {
                            $('ul.dropdown', $that).eq(0).addClass('rtl');
                        } else {
                            $('ul.dropdown', $that).eq(0).removeClass('rtl');
                        }
                    }

                });
            }, 50, 'load');
        },
        search: function() {

            var searchWrap = $("#main-search");

            $(".btn-search").click(function() {

                searchWrap.slideDown(200, 'easeOutQuad', function() {
                    $("form", this).animate({opacity: 1, left: 0}, 200, "easeOutCubic").find(".form-control").focus();
                });

                return false;
            });

            $(".close", searchWrap).click(function() {

                $("form", searchWrap).animate({opacity: 0, left: "20px"}, 200, "easeOutCubic", function() {
                    searchWrap.slideUp(200, 'easeOutQuad');
                    $(this).removeAttr('style');
                }).trigger("reset");

                return false;
            });
        },
        mobile: function() {
             $('accordion.accordion-content').show();
            // Show/Hide drop down menu
            $('.navbar .btn-navbar').click(function() {
                $('#main-menu').slideToggle(300, 'easeInOutExpo');

                return false;
            });

            // Open drop down on carret click
            $('#main-menu i.carret').on("click", function() {
				if ($(this).closest('ul').hasClass('carret')) {
                    $('#main-menu li').removeClass('active');					
                    $('#main-menu li ul.dropdown').slideUp(300, 'easeInOutExpo');
					//$(this).closest('li').children('ul.dropdown').slideDown(300, 'easeInOutExpo');
					var parent = $(this).closest('li');
					
					var children = $(this).closest('li').children('ul.dropdown');
					if(children.is(':visible')){
						parent.removeClass('active');
						children.slideUp(300, 'easeInOutExpo');					
					}
					else{
						parent.addClass('active');
						children.slideDown(300, 'easeInOutExpo');							
					}
                }
                if ($(this).closest('ul').hasClass('dropdown'))
                {                    
                    $('ul.dropdown li').removeClass('active');
                    $('ul.dropdown li ul.dropdown').slideUp(300, 'easeInOutExpo');
					
					var parent = $(this).closest('li');
					
					var children = $(this).closest('li').children('ul.dropdown');
					if(children.is(':visible')){
						parent.removeClass('active');
						children.slideUp(300, 'easeInOutExpo');					
					}
					else{
						parent.addClass('active');
						children.slideDown(300, 'easeInOutExpo');							
					}
                }
				 
                if ($(window).width() < widthMobile) {
				
                    // var parent = $(this).closest('li');

                    // if (parent.is('.active')) {
                        // parent.removeClass('active');
                    // } else {
                        // parent.addClass('active');
                    // }
                    //parent.children('ul.dropdown').slideToggle(300, 'easeInOutExpo');

                    return false;
                }
            });

            var menuLinks = $('#main-menu > li > a, #main-menu ul.dropdown > li > a');

            // Open drop down on link click
            menuLinks.on('click', function() {
                if ($(window).width() < widthMobile) {
                    if ($(this).attr('href') === '#' || $(this).attr('href') === '') {
                        $(this).children('i.carret').click();

                        return false;
                    }
                }
            });

            // Remove active class from links
            $(window).resizeComplete(function() {
                if (this.outerWidth >= widthMobile) {
                    $('#main-menu li').removeClass('active');
                    $('#main-menu ul.dropdown').css('display', '');
                }
            }, 50, 'init');

            if (isMobile) {
                menuLinks.on('click', function(event) {
                    if ($(window).width() > widthMobile && $(this).parent().children('ul.dropdown').length) {
                        if (!$(this).is('.clicked')) {
                            menuLinks.not(this).removeClass('clicked');
                            $(this).addClass('clicked');
                            event.preventDefault();
                        }
                    }
                });

                $('body > *').on('click', function(event) {
                    if (!$(event.target).parents('#main-menu').length) {
                        menuLinks.removeClass('clicked').off('mouseenter mouseleave');
                    }
                });
            }
        },
        megamenuCategory: function() {

            // Megamenu Category
            if ($('.megamenu-category').length) {

                // Navigate
                $('.category-nav li').on('mouseenter click', function(event) {

                    var $that = $(this);

                    // Check if non mobile screen
                    if ($(window).width() < widthMobile) {

                        if (event.type === 'mouseenter') { return false; }

                        if (!$that.is('.current')) { event.preventDefault(); }
                    } else {

                        // multiple click protection
                        if ($that.is('.current') && event.type === 'mouseenter') { return false; }

                    }

                    // Nav
                    $that.addClass('current').siblings().removeClass('current');

                    // Content
                    $that.closest('.megamenu-category').find('.category-content > div').eq($that.index()).addClass("current").siblings().removeClass("current");
                    $('#main-menu.custom').trigger("update");
                });

            }
        }
    },
    page_header : {
        animation: function() {

            var parallaxItem = $('#page-header *[class*="hide-to-"]');

            function parallax_init() {

                if ($(window).width() < widthMobile || isMobile) { return false; }

                var windowPosition = $(window).scrollTop();

                parallaxItem.each(function() {

                    var $that         = $(this),
                        parallaxStart = 0,
                        parallaxStep  = 300,
                        css;

                    if ($that.is('.hide-to-left')) {
                        css = { opacity: [1, 0], right: [0, "100px"] };
                    } else if ($that.is('.hide-to-right')) {
                        css = { opacity: [1, 0], left: [0, "100px"] };
                    } else if ($that.is('.hide-to-top')) {
                        css = { opacity: [1, 0], bottom: [0, "100px"] };
                    } else if ($that.is('.hide-to-bottom')) {
                        css = { opacity: [1, 0], top: [0, "100px"] };
                    }

                    $.each(css, function(parameter, value) {

                        var type = NaN,
                            i,
                            start = parseInt(value[0], 10),
                            end = parseInt(value[1], 10),
                            parallax;

                        for (i = 0; i < value.length; i += 1) {
                            if (!$.isNumeric(value[i])) {
                                type = value[i].replace(/\d+/g, '').replace('-', '');
                            }
                        }

                        if ($.isNumeric(start) && $.isNumeric(end)) {
                            if (windowPosition - parallaxStart <= 0) {
                                parallax = start;
                            } else if (windowPosition - parallaxStart >= parallaxStep) {
                                parallax = end;
                            } else {
                                parallax = start + (end - start) * ((windowPosition - parallaxStart) / parallaxStep);
                            }
                            $that.css(parameter, type ? parallax + type : parallax);
                        }
                    });
                });
            }

            if (parallaxItem.length) {
                // Call
                $(window).scroll(parallax_init).resizeComplete(parallax_init, 50, 'load');
            }
        }
    },
    container: {
        fullWidth: function() {

            var containerFullWidth = $('body > *:not(#boxed) .container-out.container-full-width');

            if (containerFullWidth.length) {
                // Call
                $(window).resizeComplete(function() {
                    containerFullWidth.width($(window).width()).css('margin-left', $('#content').offset().left * -1 + 'px');
                }, 0, 'init');
            }
        }
    },
    features : {
        lightbox : function() {

            $('.lightbox').fancybox({
                maxWidth    : 800,
                maxHeight   : 600,
                fitToView   : true,
                width       : '70%',
                height      : '70%',
                padding : 0,
                helpers : {
                    title : {
                        type    : 'over'
                    }
                },
                tpl : {
                    closeBtn    : '<a title="Close" class="btn btn-icon-close close" href="javascript:;"></a>',
                    prev        : '<a title="Previous" class="btn btn-icon-prev prev" href="javascript:;"></a>',
                    next        : '<a title="Next" class="btn btn-icon-next next" href="javascript:;"></a>'
                },
                closeSpeed : 150,
                iframe     : {
                    preload : false
                }
            });
        },
        tooltip : function() {

            $(function() {
                $("*[data-toggle=tooltip]").tooltip();
            });
        },
        placeholder : function() {

            $(function() {

                var placeholder = $('.placeholder > .form-control');

                placeholder.focus(function() {
                    $(this).parent().addClass('focus');
                }).focusout(function() {
                    $(this).parent().removeClass('focus');
                }).bind('change keyup input', function() {
                    if ($(this).val() !== '') {
                        $(this).parent().find('label').hide();
                    } else {
                        $(this).parent().find('label').show();
                    }
                });
            });
        },
        grid : function() {

            var grid = $('.grid');

            if (grid.length) {
                $(window).resizeComplete(function() {
                    grid.each(function() {

                        var $that   = $(this),
                            box     = $that.children(),
                            col     = parseFloat($that.data('columns'), 10),
                            margin  = parseInt(box.css('margin-left').replace('px', ''), 10),
                            gridWidth = $that.width() - margin,
                            newCol,
                            gridLayoutMode,
                            gridAnimation;

                        // get grid width
                        col = col || 5;

                        if (gridWidth < 1201 && gridWidth >= 900 && col > 4) { // bigger than content
                            newCol = 4;
                        } else if (gridWidth < 900 && gridWidth >= 728 && col > 3) { // iPad horizontal full width
                            newCol = 3;
                        } else if (gridWidth < 728 && gridWidth >= 480 && col > 2) { // iPhone horizontal full width
                            newCol = 2;
                        } else if (gridWidth < 480 && col > 1) { // other phones horizontal full width
                            newCol = 1;
                        } else { newCol = col; }

                        // Set new width to item
                        box.css('width', Math.floor(($that.width() - margin * newCol) / newCol) + 'px');

                        // Update slier
                        $('.slider', $that).trigger('updateSizes');

                        if ($that.is('.isotope')) {

                            // Update grid
                            $that.isotope('reLayout');

                        } else {

                            // Create grid
                            gridLayoutMode = $that.is('.posts') ? 'masonry' : 'fitRows';
                            gridAnimation = ($that.attr('data-animationEngine') === 'jquery') ? 'jquery' : 'css';

                            $that.isotope({
                                animationEngine : gridAnimation,
                                layoutMode      : gridLayoutMode,
                                resizable       : false
                            }).addClass('created');
                        }
                    });
                }, 50, 'load');
            }
        },
        comments : function() {

            var comments    = $('.comments'),
                replyBlock  = $('#reply');

            if (comments.length) {

                // Show comment form
                $('.reply a', comments).click(function() {

                    var $that = $(this);

                    replyBlock.animate({opacity: 0}, 100, function() {
                        $(this).appendTo($that.closest('.comment')).animate({opacity: 1}, 200);
                    });

                    return false;
                });

                // Hide comment form
                $('.close', replyBlock).click(function() {

                    replyBlock.animate({opacity: 0}, 100, function() {
                        $(this).appendTo($('li', comments).last()).animate({opacity: 1}, 200);
                    });

                    return false;
                });

                // Scroll to comment form
                $('.comments a.post-comment').click(function() {

                    $('html, body').animate({
                        scrollTop: replyBlock.offset().top - 500
                    }, 500);
                    $('input#name', replyBlock).focus();

                    return false;
                });
            }
        },
        form : function() {

            var $form = $('form.form-validate');

            if ($form.length) {
                $form.each(function() {

                    $(this).validate({
                        submitHandler: function(form) {
						    
                            
                            if ($(form).is('#contact-form')) { $(form).parent('.form-inner').addClass('sending'); }
							if ($(form).is('#storsimplecasestudy-form')) { $(form).parent('.form-inner').addClass('sending'); }
							if ($(form).is('#storsimplecasestudy-form')) { $("#loader").show();} 
							if ($(form).is('#casestudy-form')) { $("#loader").show();}

                            $.ajax({
                                type    : $(form).attr('method'),
                                url     : $(form).attr('action'),
                                data    : $(form).serialize(),
                                dataType: 'json',
                                success : function(data) {

                                    if ($(form).is('#contact-form')) { $(form).parent('.form-inner').removeClass('sending'); ga('send', 'event', 'button', 'click', 'contact form'); }
									if ($(form).is('#storsimplecasestudy-form')) { $(form).parent('.form-inner').removeClass('sending'); ga('send', 'event', 'SBC Adwords', 'Download Whitepaper', 'Taneja Group:Whitepaper'); }
									if ($(form).is('#storsimplecasestudy-form')){ $("#loader").hide();}
									if ($(form).is('#casestudy-form')) { $("#loader").hide();}
									
									if (data.response == "redirect") {
                                        window.location.href = data.text;
                                    }

                                    // Show response
                                    $(form).append('<div class="response ' + data.response + '">' + data.text + '</div>');

                                    // Reset form
                                    if (data.response === 'success') {
                                        $(form).trigger('reset');
                                        $('.placeholder > .form-control', form).change().focusout();
                                    }

                                    // Hide response
                                    setTimeout(function() {
                                        $('.response', $(form)).animate({left: '-15px', opacity: 0}, 300, 'easeInOutExpo', function() {
                                            $(this).slideUp(400, 'easeInOutExpo', function() {
                                                $(this).remove();
                                            });
                                        });
                                    }, 5000);
                                }
                            });

                        },
                        success: function(label, field) {},
                        errorPlacement: function(error, field) {

                            var $parent = $(field).parent('.placeholder');

                            if ($parent.length) {
                                $parent = $parent.parent();
                                $parent.find('.text-error').remove();
                                $parent.append('<span class="text-error">' + error.text() + '</span>');
                            } else {
                                $parent = $(field).parent();
                                $parent.find('.text-error').remove();
                                $parent.append('<span class="text-error">' + error.text() + '</span>');
                            }
                        }
                    });

                });
            }
        }
    },
    shortcodes : {
        teaser : function() {

            var teaser = $('.teaser');

            if (teaser.length) {
                $(window).resizeComplete(function() {
                    teaser.each(function() {
                        var $that = $('.teaser-info', $(this));
                        $that.css({marginTop: $that.height() / -2 + 'px'});
                    });
                }, 50, 'load');
            }
        },
        alertsMessages : function() {

            $('.alert .close').click(function() {
                $(this).closest('.alert').animate({left: '-50px', opacity: 0}, 300, 'easeInOutExpo', function() {
                    $(this).slideUp(400, 'easeInOutExpo', function() {
                        $(this).remove();
                    });
                });

                return false;
            });
        },
        testimonial : function() {

            var testimonial = $('.testimonial');

            if (testimonial.length) {
                $(function() {

                    // Init testimonials
                    testimonial.carouFredSel({
                        auto        : function() {
                            return $(this).attr('data-auto') === 'true' ? true : false;
                        },
                        pagination  : {
                            container: function() {
                                return $(this).closest('.testimonial-wrap').find('.testimonial-pagi');
                            },
                            anchorBuilder: function(nr, item) {
                                return '<a href="#' + nr + '">' + nr + '</a>';
                            }
                        },
                        prev        : {
                            button  : function() {
                                return $(this).closest('.testimonial-wrap').find('a.prev');
                            }
                        },
                        next        : {
                            button  : function() {
                                return $(this).closest('.testimonial-wrap').find('a.next');
                            }
                        },
                        scroll : {
                            fx          : 'crossfade',
                            duration    : 800,
                            onBefore: function(data) {

                                var $that           = $(this),
                                    testWrap        = $that.closest('.testimonial-wrap'),
                                    testHeadingCur  = $('.testimonial-heading.current', testWrap),
                                    testHeadingNew  = $('.testimonial-heading', data.items.visible);

                                testHeadingCur.animate({
                                    left    : (data.scroll.direction === 'next') ? '20px' : '-20px',
                                    opacity : 0
                                }, 400, 'easeInOutBack');

                                testHeadingNew.clone().appendTo(testWrap).css({
                                    left: (data.scroll.direction === 'next') ? '-20px' : '20px'
                                }).delay(250).animate({
                                    left    : 0,
                                    opacity : 1
                                }, 400, 'easeOutCirc', function() {
                                    testHeadingCur.remove();
                                    $(this).addClass('current').removeAttr('style');
                                });
                            }
                        },
                        width       : '100%',
                        height      : 'variable',
                        responsive  : true,
                        items       : {
                            width : 100,
                            height: 'variable'
                        },
                        onCreate    : function(data) {

                            // Variables
                            var $that       = $(this),
                                testWrap    = $that.parents('.testimonial-wrap');

                            // Process
                            testWrap.append($('.testimonial-heading', data.items[0]).clone().addClass('current')).css({
                                overflow    : 'visible',
                                height      : 'auto'
                            }).animate({
                                opacity     : 1
                            }, 500);
                        }
                    }, {
                        debug : false,
                        wrapper     : {
                            classname : 'testimonial-inner'
                        }
                    });
                });
            }
        },
        tab : function(window, $) {

            "use strict"; // jshint ;_;

            var Tab = function(element, options) {
                this.init('tab', element, options);
            };

            Tab.prototype = {

                constructor: Tab,

                init: function(type, element, options) {

                    var new_options = {},
                        navs    = $(".tab-heading > li", element),
                        current = $(".tab-heading > li.current", element),
                        tab     = $(".tab-content > div", element),
                        isVertical = $(element).is('.tab-vertical'),
                        opt;

                    $(this).each(function() {
                        $.each(element.attributes, function() {
                            if (this.specified) {
                                if (this.name.indexOf('data-') !== -1) {
                                    var type;

                                    if (this.value === 'true') {
                                        type = true;
                                    } else if (this.value === 'false') {
                                        type = false;
                                    } else {
                                        type = this.value;
                                    }
                                    new_options[this.name.replace('data-', '')] = type;
                                }
                            }
                        });
                    });

                    opt = $.extend({}, $.fn[type].defaults, new_options);

                    $(function() {

                        var active;
                        if (current.length > 1) {
                            current.each(function(i) {
                                if (i === 0) {
                                    active = $(current.get(0)).index();
                                } else {
                                    $(this).removeClass('current');
                                }
                            });
                        } else if (current.length === 1) {
                            active = $(current.get(0)).index();
                        } else {
                            active = 0;
                            navs.eq(active).addClass('current');
                        }

                        tab.each(function(i) {
                            if (i === active) {
                                $(this).addClass('current');
                            } else {
                                $(this).removeClass('current');
                            }
                        });

                    });

                    $('a', navs).click(function(e) {
                        e.preventDefault();
                    });

                    $(navs).click(function() {

                        // multiple click protection
                        if ($(element).is('.active')) { return false; }

                        // multiple click protection
                        if ($(this).is('.current')) { return false; }

                        $(this).addClass('current').siblings().removeClass('current');

                        var next = $(this).index(),
                            prev = $(".tab-content > div:visible", element).index(),
                            to,
                            from;

                        if (opt.animation === 'fade' || opt.animation === 'slide') {

                            if (opt.animation === 'fade') {
                                to   = {opacity: 0};
                                from = {opacity: 0};
                            } else {
                                if (prev > next) {
                                    to      = isVertical ? {opacity: 0, top: '30px'} : {opacity: 0, left: '30px'};
                                    from    = isVertical ? {opacity: 0, top: '-30px'} : {opacity: 0, left: '-30px'};
                                } else {
                                    to      = isVertical ? {opacity: 0, top: '-30px'} : {opacity: 0, left: '-30px'};
                                    from    = isVertical ? {opacity: 0, top: '30px'} : {opacity: 0, left: '30px'};
                                }
                            }

                            $(element).addClass('active');
                            $('.tab-content > div:visible', element).animate(to, opt.speed, 'easeInOutBack', function() {
                                $(this).hide().removeClass('current').removeAttr('style');

                                tab.eq(next).show().css(from).animate({opacity: 1, left: 0, top: 0}, opt.speed, 'easeOutCirc', function() {
                                    $(element).removeClass('active');
                                    $(this).removeAttr('style');
                                }).addClass('current');

                            });

                        } else {
                            tab.eq(next).css({display: 'block', opacity: 1}).siblings().css({display: 'none', opacity: 0});
                        }
                    });
                }
            };

            $.fn.tab = function(option) {
                return this.each(function() {
                    var $this = $(this),
                        data = $this.data('tab'),
                        options = typeof option === 'object' && option;
                    if (!data) {
                        data = new Tab(this, options);
                        $this.data('tab', data);
                    }
                    if (typeof option === 'string') { data[option](); }
                });
            };

            $.fn.tab.Constructor = Tab;

            $.fn.tab.defaults = {
                fwnavs    : false,
                animation : 'fade',
                speed     : 250
            };

            $(function() {
                $('.tab').tab();
            });
        },
        accordion : function(window, $) {

            "use strict"; // jshint ;_;

            var Accordion = function(element, options) {
                this.init('accordion', element, options);
            };

            Accordion.prototype = {

                constructor: Accordion,

                init: function(type, element, options) {

                    var new_options = {},
                        heading = $('div > .accordion-heading', element),
                        opt;

                    $(this).each(function() {
                        $.each(element.attributes, function() {
                            if (this.specified) {
                                if (this.name.indexOf('data-') !== -1) {
                                    var type;

                                    if (this.value === 'true') {
                                        type = true;
                                    } else if (this.value === 'false') {
                                        type = false;
                                    } else {
                                        type = this.value;
                                    }
                                    new_options[this.name.replace('data-', '')] = type;
                                }
                            }
                        });
                    });

                    opt = $.extend({}, $.fn[type].defaults, new_options);

                    $(heading).click(function() {

                        var block   = $(this).parent(),
                            content = $('.accordion-content', block);

                        if (opt.toggle === true) {
                            if (block.is('.active')) {
                                content.slideUp(opt.speed, 'easeInOutExpo').parent().removeClass('active');
                            } else {
                                content.slideDown(opt.speed, 'easeInOutExpo').parent().addClass('active').siblings().removeClass('active').children('.accordion-content').slideUp(opt.speed, 'easeInOutExpo');
                            }
                        } else {
                            content.slideToggle(opt.speed, 'easeInOutExpo').parent().toggleClass('active');
                        }
                    });
                    $("a", heading).click(function(e) {
                        e.preventDefault();
                    });
                }
            };

            $.fn.accordion = function(option) {
                return this.each(function() {
                    var $this = $(this),
                        data = $this.data('accordion'),
                        options = typeof option === 'object' && option;
                    if (!data) {
                        data = new Accordion(this, options);
                        $this.data('accordion', data);
                    }
                    if (typeof option === 'string') { data[option](); }
                });
            };

            $.fn.accordion.Constructor = Accordion;

            $.fn.accordion.defaults = {
                toggle: false,
                speed: 400
            };

            $(function() {
                $(".accordion").accordion();
            });
        },
        slider : function() {
            $(window).on('load', function() {
                var slider = $('.slider');

                if (slider.length) {
                    slider.each(function() {

                        var $that = $(this);

                        $that.wrap('<div class="slider-wrap"></div>').closest('.slider-wrap').prepend('<ul class="slider-nav"><li><a href="#" class="btn btn-icon-prev prev"></a></li><li><a href="#" class="btn btn-icon-next next"></a></li></ul>').find('.slider').carouFredSel({
                            auto        : {
                                play            : $that.attr('data-auto') === 'true' ? true : false,
                                timeoutDuration : $that.attr('data-duration') !== '' ? parseInt($that.attr('data-duration'), 10)  : 1000
                            },
                            scroll : {
                                fx      : $that.attr('data-animation') === 'scroll' ? 'scroll' : 'crossfade'
                            },
                            prev        : {
                                button  : function() {
                                    return $that.closest('.slider-wrap').find('a.prev');
                                }
                            },
                            next        : {
                                button  : function() {
                                    return $that.closest('.slider-wrap').find('a.next');
                                }
                            },
                            width       : '100%',
                            height      : 'variable',
                            responsive  : true,
                            items       : {
                                width : 100,
                                height: 'variable'
                            },
                            onCreate    : function(data) {
                                if (!$that.parents('.carousel, .grid').length) {
                                    $that.closest('.slider-wrap').addClass('created');
                                }
                            },
                            pagination  : {
                                anchorBuilder: function(nr, item) {
                                    return '<a href="#' + nr + '">' + nr + '</a>';
                                }
                            }
                        }, {
                            debug : false
                        });

                    });

                    slider.swipe({
                        swipeLeft: function(event, direction, distance, duration, fingerCount) {
                            $(this).trigger('next');
                        },
                        swipeRight: function(event, direction, distance, duration, fingerCount) {
                            $(this).trigger('prev');
                        }
                    });
                }
            });
        },
        carousel : function() {

            var carousel = $('.carousel');

            function carousel_visible(carousel) {

                var carouselWidth   = carousel.parents('.carousel-wrap').eq(0).width(),
                    visible         = parseFloat(carousel.data('visible'), 10),
                    newCol;

                visible = visible || 5;

                if (carouselWidth < 1201 && carouselWidth >= 984 && visible > 4) { // bigger that content
                    newCol = 4;
                } else if (carouselWidth < 984 && carouselWidth >= 751 && visible > 3) { // iPad horizontal full width
                    newCol = 3;
                } else if (carouselWidth < 751 && carouselWidth >= 480 && visible > 2) { // iPhone horizontal full width
                    newCol = 2;
                } else if (carouselWidth < 488 && visible > 1) { // other phones horizontal full width
                    newCol = 1;
                } else { newCol = visible; }
                return newCol;
            }

            if (carousel.length) {
                $(window).on('load', function() {

                    // Init carousel
                    $('.carousel').wrap('<div class="carousel-outer"><div class="carousel-inner"></div></div>').carouFredSel({
                        auto        : false,
                        prev        : {
                            button  : function() {
                                var btn = $("a.prev[href=" + $(this).attr('id') + "]");
                                return (btn.length) ? btn : $(this).closest('.carousel-wrap').find('.carousel-nav a.prev');
                            }
                        },
                        next        : {
                            button  : function() {
                                var btn = $("a.next[href=" + $(this).attr('id') + "]");
                                return (btn.length) ? btn : $(this).closest('.carousel-wrap').find('.carousel-nav a.next');
                            }
                        },
                        width       : '100%',
                        height      : 'variable',
                        responsive  : true,
                        items       : {
                            width : 100,
                            height: 'variable',
                            visible : function() {
                                return carousel_visible($(this));
                            }
                        },
                        pagination: {
                            container: function() {
                                return $(this).closest('.carousel-wrap').find('.carousel-pagi');
                            }
                        },
                        swipe       : {
                            onMouse : function() {
                                return ($(this).parents('.container-out.container-full-width').length) ? true : false;
                            }
                        },
                        onCreate    : function(data) {

                            // $(window).resize();

                            $(this).find('.slider').trigger('updateSizes');

                            $(this).closest('.carousel-wrap').delay(5000).addClass('created');
                        }
                    }, {
                        debug : false
                    });
                });

                // on Resize actions
                $(window).resizeComplete(function() {
                    carousel.each(function() {
                        $(this).trigger('configuration', ['items.visible', carousel_visible($(this))]).trigger('updateSizes').find('.slider').trigger('updateSizes');
                    });
                }, 50);

                // Swipe
                $('.container-out.container-full-width .carousel').swipe({
                    swipeLeft: function(event, direction, distance, duration, fingerCount) {
                        $(this).trigger('next');
                    },
                    swipeRight: function(event, direction, distance, duration, fingerCount) {
                        $(this).trigger('prev');
                    }
                });

                // Carousel grabbing class
                $('body').on('mousedown', '.container-full-width .caroufredsel_wrapper', function() {
                    $(this).addClass('active');
                });
                $('body').on('mouseup', '.container-full-width .caroufredsel_wrapper', function() {
                    $(this).removeClass('active');
                });

            }
        }
    },
    other : {
        project : function() {

            var project = $('.project.project-animated');

            if (project.length) {
                $(function() {
                    project.hover(function() {
                        $('.project-content', this).css('bottom', $('.project-content', this).stop().height() * -1).animate({bottom: 0}, 200);
                    }, function() {
                        $('.project-content', this).stop().animate({bottom: $('.project-content', this).outerHeight(true) * -1}, 200, function() {
                            $(this).removeAttr('style');
                        });
                    });
                });
            }
        },
        filter : function() {

            var filter = $('.project-filter'), filterTimeout;

            if (filter.length) {

                if (filter.is('.animated')) {

                    // slideToggleHor setUp
                    $('a', filter).hide();

                    $.fn.slideHorShow = function(speed, easing, callback) {
                        this.animate({
                            marginLeft      : 'show',
                            marginRight     : 'show',
                            paddingLeft     : 'show',
                            paddingRight    : 'show',
                            width           : 'show'
                        }, speed, easing, callback);
                    };
                    $.fn.slideHorHide = function(speed, easing, callback) {
                        this.animate({
                            marginLeft      : 'hide',
                            marginRight     : 'hide',
                            paddingLeft     : 'hide',
                            paddingRight    : 'hide',
                            width           : 'hide'
                        }, speed, easing, callback);
                    };

                    // show/hide/click filter
                    $('ul', filter).hover(function() {
                        var $that = this;
                        filterTimeout = setTimeout(function() {
                            $('a', $that).stop(true, true).slideHorShow(200, 'easeOutQuad');
                        }, 100);
                    }, function() {
                        clearTimeout(filterTimeout);
                        $('a', this).stop(true, true).slideHorHide(200, 'easeOutQuad');
                    });
                }

                filter.on('click', 'a', function() {

                    if ($(this).is('.active')) { return false; }

                    var o = $(this).attr('data-categories');
                    $('.project-filter-current').text((o === '*') ? 'All' : o);
                    $(this).addClass('active').parent('li').siblings().find('a').removeClass('active');
                    if (o) {
                        o = (o === '*') ? '*' : '.' + o;
                        $('.projects.isotope').isotope({ filter : o });
                    }
                    return false;
                });
            }
        },
        twitter : function() {
            $(function() {
                var tweets = $('#tweets');
                if (tweets.length) { tweets.twitterfeed(); }
            });
        },
        flickr : function() {
            $(function() {

                var flickr = $('#flickr');

                if (flickr.length) {
                    flickr.jflickrfeed({
                        limit   : 6,
                        qstrings: {
                            id: flickr.data('id')
                        },
                        itemTemplate:   '<li>' +
                                            '<a class="lightbox" href="{{image_b}}" data-fancybox-group="flickr">' +
                                                '<span class="btn btn-icon-view"></span>' +
                                                '<img src="{{image_s}}" alt="{{title}}">' +
                                            '</a>' +
                                        '</li>'
                    });
                }
            });
        },
        animation : function() {

            var animationItem = $('.animate');

            if (animationItem.length && !isMobile) {
                $(window).on('load', function() {

                    var delay;
                    animationItem.not('.animated').each(function(i) {
                        if (i !== 0 && $(this).offset().top === $(animationItem.get(i - 1)).offset().top) {
                            delay += 1;
                        } else { delay = 0; }

                        $(this).css({
                            '-webkit-animation-delay': delay * 0.1 + 's',
                            '-moz-animation-delay': delay * 0.1 + 's',
                            '-o-animation-delay': delay * 0.1 + 's',
                            '-ms-animation-delay': delay * 0.1 + 's',
                            'animation-delay': delay * 0.1 + 's'
                        });

                    });

                    setTimeout(function() {
                        $(window).scroll(function() {

                            var scrollTop = $(window).scrollTop();

                            animationItem.not('.animated').each(function() {
                                var $that   =  $(this),
                                    itemTop = $that.offset().top - $(window).height() + $that.height() / 2;

                                if (scrollTop > itemTop) { $(this).addClass('animated'); }
                            });

                        }).scroll();
                    }, 1000);


                });
            } else if (isMobile) {
                $(function() {
                    animationItem.removeClass('animate');
                });
            }
        },
        counter : function() {

            var counterItem = $('.counter');

            function counter_init() {

                var scrollTop = $(window).scrollTop();

                counterItem.not('.active').each(function() {

                    var $that   =  $(this),
                        itemTop = $that.offset().top - $(window).height() * 0.9;

                    if (scrollTop > itemTop) {
                        $(this).addClass('active');
                        $({countNum: $that.text()}).animate({countNum: $that.data('number')}, {
                            duration: 5000,
                            step: function() {
                                $that.text(Math.ceil(this.countNum));
                            }
                        });
                    }
                });
            }

            if (counterItem.length) {

                // Call
                $(window).scroll(counter_init).resizeComplete(counter_init, 100, 'init');
            }
        },
        skill : function() {

            var skillItem = $('.skill .bar.animated');

            function skill_init() {

                var scrollTop = $(window).scrollTop();

                skillItem.not('.active').each(function() {

                    var $that   =  $(this),
                        itemTop = $that.offset().top - $(window).height() * 0.9;

                    if (scrollTop > itemTop) {
                        $(this).addClass('active');
                        $({countNum: parseInt($that.text(), 10) }).animate({countNum: $that.data('value')}, {
                            duration: 2000,
                            easing: 'linear',
                            step: function() {
                                $that.text(Math.ceil(this.countNum) + '%');
                            }
                        });
                        $that.css('width', $that.data('value') + '%');
                    }
                });
            }

            if (skillItem.length) {

                // Call
                $(window).scroll(skill_init).resizeComplete(skill_init, 100, 'init');
            }
        },
        toTop : function() {
            $('#toTop').on('click', function() {
                $('html,body').animate({
                    scrollTop: 0
                }, 600, 'easeOutQuad');

                return false;
            });
        },
        registerLogin : function() {
            $(function() {
                $('.recovery-open').on('click', function() {

                    $('#recovery').css('left', '-30px').slideDown(400, 'easeInOutExpo', function() {
                        $(this).animate({left: 0, opacity: 1}, 300, 'easeInOutExpo');
                    });

                    return false;
                });
                $('.recovery-close').on('click', function() {

                    $('#recovery').animate({left: '30px', opacity: 0}, 300, 'easeInOutExpo', function() {
                        $(this).slideUp(400, 'easeInOutExpo');
                    });

                    return false;
                });

                $('.user-nav a').on('click', function() {

                    var $that = $(this),
                        userTab = $that.attr('href'),
                        userTabEq = $that.parent().index();

                    $.each(['.tab-heading > li', '.tab-content > div'], function(index, value) {
                        $(value, userTab).eq(userTabEq).addClass('current').siblings().removeClass('current');
                    });
                });
            });
        },
        sideOptions : function() {
            $(function() {

                $('.side-options-heading a').on('click', function() {
                    $(this).closest('.side-options').toggleClass('open');
                    return false;
                });

                /* Language */
                $('#language-options .language-list a').on('click', function() {

                    var $that = $(this),
                        language = $that.attr('href');

                    $('#language-options .current-language').text(language);

                    $that.addClass('current').parent().siblings().children().removeClass('current').closest('.side-options').removeClass('open');

                    return false;
                });
            });
        }
    }
};

Jets.init();

/*Expand & Show Content for About Us*/

$(document).ready(function () {
	showHideContent();
    $('div.text .more').bind('click', function () {
		if($(this).text() == "read more"){			
			$(this).text('read less');
		}
		else 
			$(this).text('read more');
        $(this).next('[class=more-text]').slideToggle('1000', 'easeInOutExpo');
    });
});

$(window).on('resize', function () {
    showHideContent();
});

function showHideContent(){
	if ($(window).width() < widthMobile) {
        $('div.text .more').hide();
        $('div.more-text').show();
    }
    else {
        $('div.text .more').show().text('read more');
        $('div.more-text').hide();
    }
}